# Generated by Django 3.2.13 on 2022-09-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220917_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contnet',
            new_name='content',
        ),
    ]
