# Generated by Django 4.1 on 2022-09-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220831_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ssafyClass',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
