# Generated by Django 4.1 on 2022-09-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_ssafyclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ssafyClass',
            new_name='ssafyclass',
        ),
    ]
